services:
  recibo-service:
    build: .
    container_name: recibo
    env_file:
      - .env
    networks:
      - recibo-network
    depends_on:
      - db
 
networks:
  recibo-network:
    driver: bridge
    external: true
volumes:
  db_data: